### ISSUE TITLE
Issues installing on embedded platforms

### ISSUE THREAD

**Issue by cyberjacob** [chardet/chardet#127]
I'm trying to install chardet on an embedded IoT platform following Requests' recent de-vendorfication (is that even a word?) of it. I'm not too familiar with chardet or it's install process, but from the looks of the log it appears to be trying to spawn a second python process using `distutils.spawn.spawn()`, which is not passing on the environment variables (`LD_LIBRARY_PATH` and `PYTHONHOME`) that Python requires to run. 

I've attached the logs below. Could you take a look and see if it's anything on your end, otherwise this will probably need to be sent upstream to distutils.

```
/system/vendor/python/bin/pip install chardet==3.0.3
  Downloading chardet-3.0.3.tar.gz (1.9Mb): 1.9Mb downloaded
  Running setup.py egg_info for package chardet
    Could not find platform independent libraries <prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    ImportError: No module named site
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/tmp/build/chardet/setup.py", line 52, in <module>
        ['chardetect = chardet.cli.chardetect:main']})
      File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/core.py", line 112, in setup
      File "/system/vendor/python/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/system/vendor/python/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/system/vendor/python/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/system/vendor/python/lib/python2.7/site-packages/pkg_resources.py", line 821, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/system/vendor/python/lib/python2.7/site-packages/pkg_resources.py", line 833, in obtain
        return installer(requirement)
      File "/system/vendor/python/lib/python2.7/site-packages/setuptools/dist.py", line 292, in fetch_build_egg
        cmd.ensure_finalized()
      File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      File "/system/vendor/python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 293, in finalize_options
        if not self.editable: self.check_site_dir()
      File "/system/vendor/python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 415, in check_site_dir
        is_site_dir = self.check_pth_processing()
      File "/system/vendor/python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 515, in check_pth_processing
        spawn([executable,'-E','-c','pass'],0)
      File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/spawn.py", line 34, in spawn
      File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/spawn.py", line 141, in _spawn_posix
    distutils.errors.DistutilsExecError: command '/system/vendor/python/bin/python-android5' failed with exit status 1
    Complete output from command python setup.py egg_info:
    Could not find platform independent libraries <prefix>

Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]

ImportError: No module named site
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/tmp/build/chardet/setup.py", line 52, in <module>
    ['chardetect = chardet.cli.chardetect:main']})
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/core.py", line 112, in setup
  File "/system/vendor/python/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/system/vendor/python/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/system/vendor/python/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/system/vendor/python/lib/python2.7/site-packages/pkg_resources.py", line 821, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/system/vendor/python/lib/python2.7/site-packages/pkg_resources.py", line 833, in obtain
    return installer(requirement)
  File "/system/vendor/python/lib/python2.7/site-packages/setuptools/dist.py", line 292, in fetch_build_egg
    cmd.ensure_finalized()
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
  File "/system/vendor/python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 293, in finalize_options
    if not self.editable: self.check_site_dir()
  File "/system/vendor/python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 415, in check_site_dir
    is_site_dir = self.check_pth_processing()
  File "/system/vendor/python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 515, in check_pth_processing
    spawn([executable,'-E','-c','pass'],0)
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/spawn.py", line 34, in spawn
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/distutils/spawn.py", line 141, in _spawn_posix
distutils.errors.DistutilsExecError: command '/system/vendor/python/bin/python-android5' failed with exit status 1

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /sdcard/com.hipipal.qpyplus/.pip/pip.log
```

**Comment by sigmavirus24** [comment]
Can you provide the following:

- Version of pip
- Version of setuptools
- Version of Python

**Comment by dan-blanchard** [comment]
This seems like it has to be a `setuptools` or a `pip` issue, because we don't spawn any processes or do anything at all fancy in `setup.py`. The [lines in question](https://github.com/chardet/chardet/blob/master/setup.py#L56-L57) are just your standard way of setting up a `console_scripts` entry point.

**Comment by pdogz** [comment]
Hi, I am trying to install chardet on a windows PC which is not accessible to the internet. My procedure is downloading the zip file, unzipping it and running the command: python setup.py install. 
When i run this command however I get the following response:

C:\Users\user\AppData\Local\Temp\Rar$DR18.356\chardet-3.0.4>
C:\Users\user\AppData\Local\Temp\Rar$DR18.356\chardet-3.0.4>python setup.py inst
all
running install
running bdist_egg
running egg_info
writing chardet.egg-info\PKG-INFO
writing dependency_links to chardet.egg-info\dependency_links.txt
writing entry points to chardet.egg-info\entry_points.txt
writing top-level names to chardet.egg-info\top_level.txt
reading manifest file 'chardet.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'requirements.txt'
writing manifest file 'chardet.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying chardet.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying chardet.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying chardet.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-I
NFO
copying chardet.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying chardet.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    ['chardetect = chardet.cli.chardetect:main']})
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\core.
py", line 148, in setup
    dist.run_commands()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.
py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.
py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\s
etuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\s
etuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.p
y", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\distutils\dist.
py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\s
etuptools\command\bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\s
etuptools\command\bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\s
etuptools\command\bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\s
etuptools\command\bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)



Could someone explain to me what you understand from this error? Thank you.

**Comment by sigmavirus24** [comment]
@pdogz can you please share your version of setuptools and the link to the `zip` file that you've downloaded? Please also note that 3.7 is not finalized yet, so there may be installation issues when using it. 3.7.0 is not planned to be released until roughly 1 month from now.
