### ISSUE TITLE
text encoding detected as windows-1255 (hebrew) while being windows-1252

### ISSUE THREAD

**Issue by celestian02** [chardet/chardet#17]
With a certain file, charted detects encoding as windows-1255. I would have thought it might be the file itself but my IDE for python development detected the encoding properly.
File link:
http://simple.podnapisi.net/fr/ppodnapisi/download/i/2292027/k/b5a3b7904326647fce0270ef3f441de7b73663af

**Comment by gargamel007** [comment]
Same here.
Chardet 2.3.0 will detect some files as windows-1255 with .99 accuracy where they actually are latin1.
Vim on the other hand gets the latin1 correct.
Please let me know if I can help narrow the cause of this.

**Comment by dan-blanchard** [comment]
Could you clone master and install it with `pip install -e /path/to/chardet/clone` and see if you still have this problem?  We need to put together a release because we've actually fixed a lot of these problems.

**Comment by celestian02** [comment]
Will do. Thanks

**Comment by gargamel007** [comment]
Hi I actually tried to install the master version on a new virtualenv with no success :( 
I get the following error : "ImportError: No module named cli.chardetect"

```
garga@Cubie:/tmp|⇒  mkdir chardetTest
garga@Cubie:/tmp|⇒  virtualenv chardetTest 
New python executable in chardetTest/bin/python
Installing setuptools, pip...done.
garga@Cubie:/tmp|⇒  chardetTest/bin/pip install https://github.com/chardet/chardet/archive/master.zip
Collecting https://github.com/chardet/chardet/archive/master.zip
  Downloading https://github.com/chardet/chardet/archive/master.zip
     / 2.2MB 296kB/s
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
Collecting enum34 (from chardet==2.3.0)
  Using cached enum34-1.0.4.tar.gz
Installing collected packages: chardet, enum34
  Running setup.py install for chardet
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    Installing chardetect script to /tmp/chardetTest/bin
  Running setup.py install for enum34
Successfully installed chardet-2.3.0 enum34-1.0.4
garga@Cubie:/tmp|⇒  chardetTest/bin/chardetect -h                    
Traceback (most recent call last):
  File "chardetTest/bin/chardetect", line 9, in <module>
    load_entry_point('chardet==2.3.0', 'console_scripts', 'chardetect')()
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cli.chardetect
garga@Cubie:/tmp|⇒  

```

**Comment by dan-blanchard** [comment]
I've never tried installing chardet with pip using the master.zip before.  I'm not sure if that works usually.  If you do:

```
pip install -e 'git+https://github.com/chardet/chardet.git#egg=chardet'
```

it should work fine.

**Comment by gargamel007** [comment]
The tarball method is quicker on big repositories. I've tried your method but ended with the same error again on a brand new virtual env using python 2.7 :(

```
garga@Cubie:/tmp|⇒  virtualenv chardetTest 
New python executable in chardetTest/bin/python
Installing setuptools, pip...done.
garga@Cubie:/tmp|⇒  chardetTest/bin/pip install -e 'git+https://github.com/chardet/chardet.git#egg=chardet'                                             
Obtaining chardet from git+https://github.com/chardet/chardet.git#egg=chardet
  Cloning https://github.com/chardet/chardet.git to ./chardetTest/src/chardet
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
Collecting enum34 (from chardet)
  Using cached enum34-1.0.4.tar.gz
Installing collected packages: enum34, chardet
  Running setup.py install for enum34
  Running setup.py develop for chardet
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    Creating /tmp/chardetTest/lib/python2.7/site-packages/chardet.egg-link (link to .)
    Adding chardet 2.3.0 to easy-install.pth file
    Installing chardetect script to /tmp/chardetTest/bin
    Installed /tmp/chardetTest/src/chardet
Successfully installed chardet enum34-1.0.4
garga@Cubie:/tmp|⇒  chardetTest/bin/chardetect 
Traceback (most recent call last):
  File "chardetTest/bin/chardetect", line 9, in <module>
    load_entry_point('chardet==2.3.0', 'console_scripts', 'chardetect')()
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/tmp/chardetTest/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cli.chardetect
```

**Comment by sigmavirus24** [comment]
See #55.

**Comment by gargamel007** [comment]
Thanks. I've just tested the latest commit and my issue is fixed. My file is now recognized as a  windows-1252 but with confidence 0.73. The main issue seems fixed :)

**Comment by celestian02** [comment]
I can confirm I get a better behavior as well, sorry for the delay in testing and many thanks for the fix!
