### ISSUE TITLE
4.0.0: sphinx 4.0.2 warnings

### ISSUE THREAD

**Issue by kloczek** [chardet/chardet#227]
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
/usr/lib/python3.8/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '5.0.0dev0' to '5.0.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running build_sphinx
Running Sphinx v4.0.2
/usr/lib/python3.8/site-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (5.0.0dev0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 7 added, 0 changed, 0 removed
reading sources... [100%] usage
WARNING: autodoc: failed to import module 'chardetect' from module 'chardet'; the following exception was raised:
No module named 'chardet.chardetect'
WARNING: autodoc: failed to import module 'compat' from module 'chardet'; the following exception was raised:
No module named 'chardet.compat'
WARNING: autodoc: failed to import module 'constants' from module 'chardet'; the following exception was raised:
No module named 'chardet.constants'
WARNING: autodoc: failed to import module 'langcyrillicmodel' from module 'chardet'; the following exception was raised:
No module named 'chardet.langcyrillicmodel'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... chardet.1 { faq supported-encodings usage how-it-works api/modules api/chardet } done
build succeeded, 5 warnings.
```

**Comment by kloczek** [comment]
BTW do you have any plans to make new release? :)

**Comment by kloczek** [comment]
I cannot find any commits related to that issue.
May I ask to drop commits hashes?

**Comment by kloczek** [comment]
Tested 5.0.0.
In mean time I've switched to usie`sphinx-build` command (setuptools<>sphinx integration is now marked as deprecated).
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/chardet-5.0.0/docs/conf.py", line 15, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/chardet-5.0.0/docs/conf.py", line 15, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/chardet-5.0.0/docs/conf.py", line 15, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```
To fix that looks  like it is necessary to appluy small patch for conf.py
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -11,13 +11,14 @@
 # serve to show the default.

 import os
-
-import chardet
+import sys

 # If extensions (or modules to document with autodoc) are in another directory,
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
-# sys.path.insert(0, os.path.abspath('.'))
+sys.path.insert(0, os.path.abspath(".."))
+
+import chardet

 # -- General configuration ------------------------------------------------
```
With that patch however still there are some warnings
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2
/usr/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.1.0) doesn't match a supported version!
  warnings.warn(
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 7 added, 0 changed, 0 removed
reading sources... [100%] usage
WARNING: autodoc: failed to import module 'chardetect' from module 'chardet'; the following exception was raised:
No module named 'chardet.chardetect'
WARNING: autodoc: failed to import module 'compat' from module 'chardet'; the following exception was raised:
No module named 'chardet.compat'
WARNING: autodoc: failed to import module 'constants' from module 'chardet'; the following exception was raised:
No module named 'chardet.constants'
WARNING: autodoc: failed to import module 'langcyrillicmodel' from module 'chardet'; the following exception was raised:
No module named 'chardet.langcyrillicmodel'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-chardet.3 { faq supported-encodings usage how-it-works api/modules api/chardet } done
build succeeded, 5 warnings.
```
All because there is no thise submodules in source tree
```console
[tkloczko@devel-g2v chardet-5.0.0]$ ls chardet/chardetect* chardet/compat* chardet/constants* chardet/langcyrillicmodel*
ls: cannot access 'chardet/chardetect*': No such file or directory
ls: cannot access 'chardet/compat*': No such file or directory
ls: cannot access 'chardet/constants*': No such file or directory
ls: cannot access 'chardet/langcyrillicmodel*': No such file or directory
```
So looks like documentation is outdated.
