### ISSUE TITLE
检测不出pdf编码

### ISSUE THREAD

**Issue by vdjango** [chardet/chardet#234]
import textract
text = textract.process("/Users/code/test.pdf", encoding='utf-8')

textract/parsers/utils.py打印encoding结果为None

部分pdf好使，部分不好受

Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Users/junsi/opt/miniconda3/envs/extract_text/lib/python3.8/site-packages/textract/parsers/__init__.py", line 77, in process
    return parser.process(filename, encoding, **kwargs)
  File "/Users/junsi/opt/miniconda3/envs/extract_text/lib/python3.8/site-packages/textract/parsers/utils.py", line 47, in process
    unicode_string = self.decode(byte_string)
  File "/Users/junsi/opt/miniconda3/envs/extract_text/lib/python3.8/site-packages/textract/parsers/utils.py", line 66, in decode
    return text.decode(result['encoding'])
TypeError: decode() argument 'encoding' must be str, not None

**Comment by KSneijders** [comment]
This issue seems to be about `textract`. This is the chardet repo.
You can find textract here: https://github.com/deanmalmgren/textract
