### ISSUE TITLE
chardet 5.0 KeyError with Python 3.10 on Windows 

### ISSUE THREAD

**Issue by cas--** [chardet/chardet#265]
Yesterday I encountered a strange CI failure for our Windows GitHub CI workflows which had been running fine until then. The Python 3.7 job passed fine but the Python 3.10 job failed.

https://github.com/deluge-torrent/deluge/actions/workflows/ci.yml?query=branch%3Adevelop

The only difference I could find from a diff of the logs was the new chardet 5.0.0 being pulled in. So I pinned chardet to 4.0.0 and CI is passing again. 

GitHub Actions Environment:
```
Virtual Environment: windows-2022 (20220626.1)
Python 3.10.5
```
Just to note that I also tested same error occurs with windows-2019.

The traceback is rather cryptic since it comes from pytest but this is all there is from the job:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\_pytest\main.py", line 264, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\_pytest\config\__init__.py", line 995, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\pluggy\_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\hostedtoolcache\windows\Python\3.10.5\x64\lib\site-packages\_pytest\faulthandler.py", line 27, in pytest_configure
INTERNALERROR>     import faulthandler
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 171, in __enter__
INTERNALERROR>   File "<frozen importlib._bootstrap>", line 123, in acquire
INTERNALERROR> KeyError: 1832
```

**Comment by dan-blanchard** [comment]
Well, that's a baffling one.

**Comment by cas--** [comment]
It is rather confounding but I have narrowed it down to this commit: https://github.com/chardet/chardet/commit/322229573173307e1380eb151ea446b8c6fe2c3b

And looks to be related to importing the module rather than usage, as suspected from pytest traceback, and I'll continue to investigate when I have a spare moment

Testing with 3.8 and 3.9 didn't show any issues, just 3.10 affected

**Comment by jayaddison** [comment]
(:wave: I landed here as part of reading the state of any bugs related to `chardet` v5.0.0)

Although I'm not 100% certain, it looks like this could be related to the issue described in [python/cpython#/91351](https://github.com/python/cpython/issues/91351) -- the lock-acquisition methods named in the stacktrace are the same, and so is the exception class raised.

**Comment by dan-blanchard** [comment]
I added Mac and Windows testing to our build matrix in #267 and I can't reproduce this issue.

**Comment by jayaddison** [comment]
The (likely intermittent) issue that appeared here has, I think, been [resolved by `gh-91351` in v3.12a5 of Python](https://docs.python.org/3.12/whatsnew/changelog.html?highlight=gh-91351#id10).  It's still a while until the scheduled [release of Py3.12 final](https://peps.python.org/pep-0693/) -- to mention nothing of CI config for `chardet` -- so maybe it's a distraction to even mention - but I get the sense that this has been resolved.

**Comment by dan-blanchard** [comment]
This was a bug specific to chardet 5.0.0 and has been resolved. chardet 7.0, which will be released shortly, is a ground-up rewrite that does not have this issue.

**Comment by jayaddison** [comment]
NB: for anyone considering an upgrade to v7 to avoid this bug: please note that the licensing of the library has changed in that version.

**Comment by dan-blanchard** [comment]
Yes, it has been changed to the less restrictive MIT license so that more projects can use it without issue.
